name: Spell checking
on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request_target:
  issue_comment:
    types: [created]

jobs:
  spelling:
    name: Spell checking
    permissions:
      contents: read
      pull-requests: read
    if: "contains(github.event_name, 'pull_request') || github.event_name == 'push'"
    uses: jsoref/check-spelling/.github/workflows/spell-check.yml@reusable
    with:
      experimental_apply_changes_via_bot: true

  comment:
    name: Comment
    needs: spelling
    permissions:
      contents: write
      pull-requests: write
    if: always() && needs.spelling.result == 'failure'
    uses: jsoref/check-spelling/.github/workflows/comment.yml@reusable
    with:
      experimental_apply_changes_via_bot: true
      artifact_name: ${{ needs.spelling.outputs.artifact_name }}

  update:
    name: Update PR
    permissions:
      contents: write
      pull-requests: write
    if: ${{
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        contains(github.event.comment.body, '@check-spelling-bot apply')
      }}
    uses: jsoref/check-spelling/.github/workflows/update.yml@reusable
